# Generated by Django 3.1.3 on 2020-12-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0019_auto_20201205_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='attack_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='command',
            field=models.CharField(max_length=100),
        ),
    ]
