# Generated by Django 3.1.3 on 2020-12-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0020_auto_20201209_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
