# Generated by Django 3.1.3 on 2020-12-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0021_auto_20201209_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='height_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
