# Generated by Django 3.1.3 on 2021-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0023_character_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='base_damage',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
