# Generated by Django 2.2.16 on 2020-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0002_remove_character_slug_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
