# Generated by Django 2.2.16 on 2020-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0004_auto_20201111_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug_source',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='command',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='specialstance',
            name='abbreviation',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
