# Generated by Django 2.2.16 on 2020-11-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0005_auto_20201111_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('abbreviation', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='move',
            name='type_entry',
        ),
        migrations.AlterField(
            model_name='move',
            name='command',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='specialstance',
            name='abbreviation',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='specialstance',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='move',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='soulcalibur_vi.Section'),
            preserve_default=False,
        ),
    ]
