# Generated by Django 2.2.16 on 2020-11-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0007_auto_20201112_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soulcalibur_vi.Section'),
        ),
    ]
