# Generated by Django 2.2.16 on 2020-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0009_auto_20201112_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='height_level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='HeightLevel',
        ),
    ]
