# Generated by Django 2.2.16 on 2020-11-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0011_specialstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialstate',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
