# Generated by Django 2.2.16 on 2020-11-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0013_auto_20201115_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialstance',
            name='abbreviation',
            field=models.CharField(max_length=30),
        ),
    ]
