# Generated by Django 2.2.16 on 2020-11-16 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0014_auto_20201115_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_character', to='soulcalibur_vi.Character'),
        ),
    ]
