# Generated by Django 2.2.16 on 2020-11-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soulcalibur_vi', '0015_auto_20201116_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_section', to='soulcalibur_vi.Section'),
        ),
    ]
